### ISSUE TITLE
`ts-node index.ts` fails

### ISSUE THREAD

**Issue by KirillLykov** [godmodegalactus/configure_mango#1]
I'm trying to set up all the components to run mango_bench.
My understanding is that I need to do both: launch validator and setup/run mango using TS scripts:
```bash
 ./configure_local.sh  
 ts-node index.ts
 ts-node keeper.ts
 ```
 
 Yet the second step fails:
 ```bash
 $ ts-node index.ts
 /usr/local/lib/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:3:23 - error TS2307: Cannot find module '@blockworks-foundation/mango-client' or its corresponding type declarations.

3 import { sleep } from "@blockworks-foundation/mango-client";
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
  diagnosticCodes: [ 2307 ]
}

$ ts-node --version
v10.9.1
```

**Comment by godmodegalactus** [comment]
Hey,

Have you done `npm install` on your configure mango directory. It should install the necessary mango-client-v3.

**Comment by KirillLykov** [comment]
> Hey,
> 
> Have you done `npm install` on your configure mango directory. It should install the necessary mango-client-v3.

Yeah, I think so. TS is absolute magic for me but I've followed the instructions.
The full output looks like:
```bash
➜  configure_mango (main) npm install                         ✱

changed 1 package, and audited 97 packages in 518ms

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  configure_mango (main) ts-node index.ts                  ✭ ✱
/usr/local/lib/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:3:23 - error TS2307: Cannot find module '@blockworks-foundation/mango-client' or its corresponding type declarations.

3 import { sleep } from "@blockworks-foundation/mango-client";
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
  diagnosticCodes: [ 2307 ]
}
```

**Comment by godmodegalactus** [comment]
> > Hey,
> > 
> > Have you done `npm install` on your configure mango directory. It should install the necessary mango-client-v3.
> 
> Yeah, I think so. TS is absolute magic for me but I've followed the instructions.
> The full output looks like:
> ```bash
> ➜  configure_mango (main) npm install                         ✱
> 
> changed 1 package, and audited 97 packages in 518ms
> 
> 11 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> ➜  configure_mango (main) ts-node index.ts                  ✭ ✱
> /usr/local/lib/node_modules/ts-node/src/index.ts:859
>     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
>            ^
> TSError: ⨯ Unable to compile TypeScript:
> index.ts:3:23 - error TS2307: Cannot find module '@blockworks-foundation/mango-client' or its corresponding type declarations.
> 
> 3 import { sleep } from "@blockworks-foundation/mango-client";
>                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
>     at createTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:859:12)
>     at reportTSError (/usr/local/lib/node_modules/ts-node/src/index.ts:863:19)
>     at getOutput (/usr/local/lib/node_modules/ts-node/src/index.ts:1077:36)
>     at Object.compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1433:41)
>     at Module.m._compile (/usr/local/lib/node_modules/ts-node/src/index.ts:1617:30)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
>     at Object.require.extensions.<computed> [as .ts] (/usr/local/lib/node_modules/ts-node/src/index.ts:1621:12)
>     at Module.load (node:internal/modules/cjs/loader:1037:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:878:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:82:12) {
>   diagnosticCodes: [ 2307 ]
> }
> ```

Hey could you do following  and let me know if it works.

`npm install "@blockworks-foundation/mango-client"`

**Comment by KirillLykov** [comment]
@godmodegalactus I've found that packages are defined in json file in the folder, and that it requires that mango repo is cloned next to this repo. So I did this and got:
```
➜  configure_mango (main) npm install                       ✭ ✱
npm ERR! code 1
npm ERR! path /home/klykov/wrks/mango-client-v3
npm ERR! command failed
npm ERR! command sh -c -- yarn clean && yarn build
npm ERR! yarn run v1.22.19
npm ERR! $ rm -rf lib
npm ERR! Done in 0.05s.
npm ERR! yarn run v1.22.19
npm ERR! $ tsc
npm ERR! src/client.ts(1838,32): error TS4073: Parameter 'bookSideInfo' of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/client.ts(1935,34): error TS4073: Parameter 'options' of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/client.ts(4461,32): error TS4073: Parameter 'bookSideInfo' of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/client.ts(5347,59): error TS4055: Return type of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/config.ts(273,17): error TS4078: Parameter 'key' of exported function has or is using private name 'Buffer'.
npm ERR! src/config.ts(294,18): error TS4078: Parameter 'mint' of exported function has or is using private name 'Buffer'.
npm ERR! src/instruction.ts(2351,15): error TS4078: Parameter 'referrerId' of exported function has or is using private name 'Buffer'.
npm ERR! src/layout.ts(112,13): error TS4073: Parameter 'b' of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/layout.ts(116,21): error TS4073: Parameter 'b' of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/layout.ts(120,14): error TS4073: Parameter 'b' of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/layout.ts(208,13): error TS4073: Parameter 'b' of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/scripts/loggable.ts(136,11): error TS4078: Parameter 'buffer' of exported function has or is using private name 'Buffer'.
npm ERR! src/utils/fixednum.ts(108,23): error TS4073: Parameter 'ArrayType' of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/utils/fixednum.ts(111,6): error TS4055: Return type of public method from exported class has or is using private name 'Buffer'.
npm ERR! src/utils/utils.ts(375,61): error TS4060: Return type of exported function has or is using private name 'Buffer'.
npm ERR! src/utils/utils.ts(429,30): error TS4060: Return type of exported function has or is using private name 'Buffer'.
npm ERR! tsconfig.json(2,14): error TS6053: File '@tsconfig/recommended/tsconfig.json' not found.
npm ERR! tsconfig.json(13,5): error TS5070: Option '--resolveJsonModule' cannot be specified without 'node' module resolution strategy.
npm ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
npm ERR! error Command failed with exit code 1.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/klykov/.npm/_logs/2022-10-26T11_10_52_258Z-debug-0.log
```

Let me try to `npm install "@blockworks-foundation/mango-client"` and remove cloned mango repo:

```
➜  configure_mango (main) npm install "@blockworks-foundation/mango-client"

changed 1 package, and audited 97 packages in 520ms

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
➜  configure_mango (main) ts-node index.ts                  ✭ ✱ /usr/local/lib/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:3:23 - error TS2307: Cannot find module '@blockworks-foundation/mango-client' or its corresponding type declarations.

3 import { sleep } from "@blockworks-foundation/mango-client";
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
```

**Comment by godmodegalactus** [comment]
Can i know which version of nodejs you are using.
`node --version`

**Comment by KirillLykov** [comment]
> Can i know which version of nodejs you are using. `node --version`

```
 node --version                    ✭ ✱
v19.0.0
```

**Comment by godmodegalactus** [comment]
> > Can i know which version of nodejs you are using. `node --version`
> 
> ```
>  node --version                    ✭ ✱
> v19.0.0
> ```

Hey I found the solution. You have to do :
`yarn add @blockworks-foundation/mango-client` in the solution.

I will also update the readme file accordingly. 
Let me know if it works.

**Comment by KirillLykov** [comment]
Looks resolved now
